### ISSUE TITLE
stop NetworkManager from overwritting resolv.conf

### ISSUE THREAD

**Issue by kostyrev** [picotrading/ansible-resolv_conf#1]
Hello!
I'd like to know would it be appropriate (merged) if I added task that stops subj?
As in https://wiki.archlinux.org/index.php/Resolv.conf#With_NetworkManager

**Comment by jtyr** [comment]
To stop NetworkManager from overwriting the `resolv.conf` file, you have to configure the NetworkManager. This role configures only the `resolv.conf`.  As I don't have any Ansible role to configure NetworkManager, I suggest you create your own role to do that.

This issue can be closed as `WONTFIX`.

**Comment by kostyrev** [comment]
Yeah. I thought so. But asked just in case.
